### ISSUE TITLE
请问如何添加需要的诗词?

### ISSUE THREAD

**Issue by leyiang** [xxnuo/jizhi-mod#2]
大佬好！
我在源码里看到诗词来自`"sentences-bundle/sentences/i.json"`, 但是没找到这个文件, 下载Release也没看到。
如果要添加一些语句该怎么做呢？

**Comment by xxnuo** [comment]
目前没有添加自定义诗词的功能，我加入计划中吧

**Comment by leyiang** [comment]
> 目前没有添加自定义诗词的功能，我加入计划中吧

我指的是修改文件，自己编译，原有的诗词信息我没找到。
这个诗词信息是在哪呢? 修改好编译应该就行了吧？

**Comment by xxnuo** [comment]
在 node_modules 里面

**Comment by xxnuo** [comment]
1.1.0 新版本优化了插件包大小（60MB->7MB），
因为使用了按需生成字体文件技术，所以添加自定义诗词可能会导致缺失部分字符的字体。
如果你想添加的诗词可以写在这里，我这里帮你添加上去

**Comment by leyiang** [comment]
不好意思，我不太看邮件，漏了你的回复，现在没什么想加的了（有一次刷新看到了菜根谭，原来已经在里面了）
