### ISSUE TITLE
切换主题颜色无法保存？

### ISSUE THREAD

**Issue by jiangfengshanyue** [xxnuo/jizhi-mod#3]
安装后默认是浅色。
点击左下角主题颜色切换按钮，设置为深色。
然后刷新当前标签页，或者新建标签页，主题颜色会恢复成浅色。
这是bug？还是就这样设计的？

**Comment by xxnuo** [comment]
第一版是这样设计的

**Comment by xxnuo** [comment]
下一版会对添加背景功能，适配好后会保存颜色模式的状态。
我想想怎么美观怎么来😀

**Comment by xxnuo** [comment]
发布了一个小版本，会保存颜色选择结果，插件商店审核通过后更新即可👌
