### ISSUE TITLE
诗句作者姓名在红色印章背景中并不居中。

### ISSUE THREAD

**Issue by jiangfengshanyue** [xxnuo/jizhi-mod#4]
诗句作者姓名在红色印章背景中并不居中。
![诗句作者姓名在红色印章背景中并不居中。](https://github.com/user-attachments/assets/53de9446-4b40-444f-bfb2-8bf3b671e579)

**Comment by xxnuo** [comment]
这是一个比较麻烦的问题，因为每个字体的留白和对齐方式都不同，代码让一个对齐了另一个又会不怎么居中。
我得想想用什么方案修复这个问题，有大佬能留下建议也好～

**Comment by xxnuo** [comment]
新版修复了，正在审核中，如果还有问题重新打开issue 👌
