### ISSUE TITLE
bug: firefox 设置了严格的隐私策略后，每次主题页都会重新进入引导界面

### ISSUE THREAD

**Issue by Redias** [xxnuo/jizhi-mod#9]
如题，虽然目前引导只有4步，但每次点一下比较麻烦。我习惯不留痕，所以这个设置可能在cookie里每次关闭页面浏览器后被清掉了，如果能优化下也许使用上更好

**Comment by xxnuo** [comment]
你这个不好实现，除非让所有人都不能使用引导了，但这个不太可能

**Comment by xxnuo** [comment]
经过我的测试，严格模式下完全可以正常使用，你是选了自定义设置了 cookie 策略吧。
<img width="688" alt="image" src="https://github.com/user-attachments/assets/07aa4772-9661-46a9-acd2-d40487f5b869">

你如果设置里不保留 cookie，那和无痕模式没啥差别，不能保存信息。

在 Firefox 的隐私浏览模式或无痕模式下，浏览器会限制网页保存本地数据的能力。这是为了保护用户的隐私，防止在隐私浏览会话结束后留下任何痕迹。以下是一些常见的本地数据存储方式以及它们在严格模式下的行为：

### 1. **Cookies**
   - **行为**: 在严格模式下，Firefox 不会保存任何新的 Cookies。现有的 Cookies 也不会被读取或写入。
   - **限制**: 网页无法在严格模式下创建或访问 Cookies。

### 2. **Local Storage**
   - **行为**: 在严格模式下，Firefox 不会保存任何新的 Local Storage 数据。现有的 Local Storage 数据也不会被读取或写入。
   - **限制**: 网页无法在严格模式下创建或访问 Local Storage。

### 3. **Session Storage**
   - **行为**: 在严格模式下，Session Storage 仍然可以被使用，但数据仅在当前会话中有效。一旦会话结束（例如关闭标签页或窗口），Session Storage 中的数据将被清除。
   - **限制**: 数据不会持久化，仅在当前会话中可用。

### 4. **IndexedDB**
   - **行为**: 在严格模式下，Firefox 不会保存任何新的 IndexedDB 数据。现有的 IndexedDB 数据也不会被读取或写入。
   - **限制**: 网页无法在严格模式下创建或访问 IndexedDB。

### 5. **Cache**
   - **行为**: 在严格模式下，Firefox 不会保存任何新的缓存数据。现有的缓存数据也不会被读取或写入。
   - **限制**: 网页无法在严格模式下创建或访问缓存数据。

### 6. **WebSQL**
   - **行为**: WebSQL 已经被废弃，不建议使用。在严格模式下，Firefox 不会支持 WebSQL。
   - **限制**: 网页无法在严格模式下使用 WebSQL。

### 7. **FileSystem API**
   - **行为**: FileSystem API 在严格模式下不可用。
   - **限制**: 网页无法在严格模式下使用 FileSystem API。

### 总结
在 Firefox 的严格模式下，网页无法保存任何持久化的本地数据（如 Cookies、Local Storage、IndexedDB 等）。Session Storage 可以在当前会话中使用，但会话结束后数据会被清除。这种设计确保了用户的隐私，防止在隐私浏览会话结束后留下任何痕迹。
